reorder_imports = true
edition = "2021"
indent_style = "Block"
hard_tabs = true
merge_derives = true 
newline_style = "Unix" 
remove_nested_parens = true
reorder_modules = true
tab_spaces = 4
use_try_shorthand = true
